"""Phase Locking Value (PLV): the falsification metric.

    PLV = |mean(exp(i · (φ_x(t) − φ_y(t))))| over T samples

PLV ∈ [0, 1]:
    0 → no phase relationship (random phase difference)
    1 → perfect phase locking

The falsifiable predicate:
    PLV(neural_phase, market_phase) > 0  on held-out intraday data.

Statistical significance is assessed by:
    1. Surrogate test: shuffle φ_y(t) to destroy temporal structure,
       compute PLV_surrogate, repeat N times.
    2. p-value = P(PLV_surrogate ≥ PLV_observed).

INVARIANT: PLV must always be computed on held-out data.
           In-sample PLV is not reported.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from numpy.typing import NDArray


@dataclass(frozen=True)
class PLVResult:
    plv: float
    p_value: float
    n_surrogates: int
    significant: bool
    alpha: float


def plv(
    phi_x: NDArray[np.floating],
    phi_y: NDArray[np.floating],
) -> float:
    """Compute Phase Locking Value between two phase series.

    Parameters
    ----------
    phi_x, phi_y : ndarray, shape (T,)
        Instantaneous phase series in radians.

    Returns
    -------
    float
        PLV in [0, 1].
    """
    if len(phi_x) != len(phi_y):
        raise ValueError("phi_x and phi_y must have the same length")
    delta = phi_x - phi_y
    return float(np.abs(np.mean(np.exp(1j * delta))))


def plv_significance(
    phi_x: NDArray[np.floating],
    phi_y: NDArray[np.floating],
    n_surrogates: int = 1000,
    alpha: float = 0.05,
    seed: int = 42,
) -> PLVResult:
    """Assess statistical significance of PLV via surrogate test.

    The null hypothesis: φ_x and φ_y have no consistent phase relationship.
    Surrogates are generated by random cyclic shifts of φ_y, which preserves
    its autocorrelation structure while destroying cross-signal phase locking.

    Parameters
    ----------
    phi_x, phi_y : ndarray, shape (T,)
        Phase series on held-out data only.
    n_surrogates : int
        Number of surrogate samples.
    alpha : float
        Significance level.
    seed : int
        Reproducibility seed.

    Returns
    -------
    PLVResult
        Observed PLV, p-value, and significance flag.
    """
    observed = plv(phi_x, phi_y)
    rng = np.random.default_rng(seed)
    T = len(phi_y)

    surrogate_plvs = np.empty(n_surrogates, dtype=float)
    for i in range(n_surrogates):
        shift = rng.integers(1, T)
        phi_y_shifted = np.roll(phi_y, shift)
        surrogate_plvs[i] = plv(phi_x, phi_y_shifted)

    p_value = float(np.mean(surrogate_plvs >= observed))

    return PLVResult(
        plv=observed,
        p_value=p_value,
        n_surrogates=n_surrogates,
        significant=p_value < alpha,
        alpha=alpha,
    )


def rolling_plv(
    phi_x: NDArray[np.floating],
    phi_y: NDArray[np.floating],
    window: int,
) -> NDArray[np.floating]:
    """Compute PLV in a rolling window.

    Parameters
    ----------
    phi_x, phi_y : ndarray, shape (T,)
    window : int

    Returns
    -------
    ndarray, shape (T - window + 1,)
    """
    T = len(phi_x)
    n_out = T - window + 1
    result = np.empty(n_out, dtype=float)
    for i in range(n_out):
        result[i] = plv(phi_x[i : i + window], phi_y[i : i + window])
    return result
