"""M1 — contract tests for the system-invariants monograph generator.

This test file is the HN29 binding. It locks in:

1. **Determinism.** :func:`generate_monograph` is a pure
   function of its inputs. Two calls with the same registry +
   state machine produce byte-identical output.
2. **CI guard.** The committed
   ``docs/monograph/INVARIANTS_MONOGRAPH.md`` matches the live
   generator output byte-for-byte. Any new HN added to
   ``INVARIANTS.yaml`` without regenerating the monograph fails
   this test.
3. **Header marker present.** Every generated monograph carries
   the stable ``GENERATED BY neurophase.governance.monograph``
   marker as its first line; a hand-edited file cannot
   impersonate the generator.
4. **Coverage.** Every invariant id in the registry appears as
   a section heading in the rendered output. Every honest-naming
   id appears as well.
5. **State coverage.** Every gate state from
   ``STATE_MACHINE.yaml`` appears in the rendered state table.
6. **Test bindings surfaced.** Every pytest node id bound to
   any contract is rendered verbatim in the monograph (so a
   reviewer can grep the doc for a test name and find which
   contract owns it).
"""

from __future__ import annotations

from pathlib import Path

from neurophase.governance.invariants import load_registry
from neurophase.governance.monograph import (
    GENERATED_HEADER_MARKER,
    MONOGRAPH_PATH,
    generate_monograph,
    write_monograph,
)
from neurophase.governance.state_machine import load_state_machine

REGISTRY = load_registry()
STATE_MACHINE = load_state_machine()


# ---------------------------------------------------------------------------
# 1. Determinism.
# ---------------------------------------------------------------------------


class TestDeterminism:
    def test_two_calls_byte_identical(self) -> None:
        a = generate_monograph(registry=REGISTRY, state_machine=STATE_MACHINE)
        b = generate_monograph(registry=REGISTRY, state_machine=STATE_MACHINE)
        assert a == b

    def test_default_load_matches_explicit_load(self) -> None:
        explicit = generate_monograph(registry=REGISTRY, state_machine=STATE_MACHINE)
        default = generate_monograph()
        assert explicit == default


# ---------------------------------------------------------------------------
# 2. CI guard — committed doc matches live generator output.
# ---------------------------------------------------------------------------


class TestCommittedFileMatches:
    def test_committed_monograph_exists(self) -> None:
        assert MONOGRAPH_PATH.is_file(), (
            f"committed monograph not found at {MONOGRAPH_PATH}; "
            "run `python -c 'from neurophase.governance.monograph "
            "import write_monograph; write_monograph()'` and commit"
        )

    def test_committed_monograph_matches_generator(self) -> None:
        """The committed file must equal the live generator output
        BYTE-FOR-BYTE. Any new contract in INVARIANTS.yaml that
        is not reflected in docs/monograph/INVARIANTS_MONOGRAPH.md
        fails this test."""
        committed = MONOGRAPH_PATH.read_text(encoding="utf-8")
        live = generate_monograph()
        if committed != live:
            # Surface a useful diff hint without dumping the full
            # 45 KB to the test report.
            committed_lines = committed.splitlines()
            live_lines = live.splitlines()
            diff_count = sum(
                1
                for c_line, l_line in zip(committed_lines, live_lines, strict=False)
                if c_line != l_line
            )
            length_diff = len(live_lines) - len(committed_lines)
            raise AssertionError(
                f"docs/monograph/INVARIANTS_MONOGRAPH.md is stale: "
                f"{diff_count} line(s) differ, line-count delta = "
                f"{length_diff:+d}. Run "
                f"`python -c 'from neurophase.governance.monograph "
                f"import write_monograph; write_monograph()'` and "
                f"commit the result."
            )


# ---------------------------------------------------------------------------
# 3. Header marker.
# ---------------------------------------------------------------------------


class TestHeaderMarker:
    def test_first_line_is_marker(self) -> None:
        text = generate_monograph()
        first_line = text.splitlines()[0]
        assert first_line == GENERATED_HEADER_MARKER

    def test_marker_appears_in_committed_file(self) -> None:
        text = MONOGRAPH_PATH.read_text(encoding="utf-8")
        assert GENERATED_HEADER_MARKER in text


# ---------------------------------------------------------------------------
# 4. Coverage — every invariant + every honest-naming contract is rendered.
# ---------------------------------------------------------------------------


class TestCoverage:
    def test_every_invariant_id_in_output(self) -> None:
        text = generate_monograph()
        for inv in REGISTRY.invariants:
            assert f"### {inv.id}" in text, f"missing section for {inv.id}"

    def test_every_invariant_statement_in_output(self) -> None:
        text = generate_monograph()
        for inv in REGISTRY.invariants:
            # The statement is rendered verbatim — check a stable
            # 30-character prefix.
            prefix = inv.statement[:30]
            assert prefix in text, f"missing statement for {inv.id}"

    def test_every_honest_naming_id_in_output(self) -> None:
        text = generate_monograph()
        for hn in REGISTRY.honest_naming:
            assert f"### {hn.id}" in text, f"missing section for {hn.id}"


# ---------------------------------------------------------------------------
# 5. State machine coverage.
# ---------------------------------------------------------------------------


class TestStateMachineCoverage:
    def test_every_gate_state_in_output(self) -> None:
        text = generate_monograph()
        for state in STATE_MACHINE.states:
            assert f"`{state.name}`" in text, f"missing state {state.name}"

    def test_every_transition_in_output(self) -> None:
        text = generate_monograph()
        for transition in STATE_MACHINE.transitions:
            assert f"`{transition.target}`" in text, (
                f"missing transition target {transition.target}"
            )


# ---------------------------------------------------------------------------
# 6. Test bindings surfaced verbatim.
# ---------------------------------------------------------------------------


class TestBindingsSurfaced:
    def test_invariant_test_ids_appear_in_output(self) -> None:
        """Every test id bound to an invariant appears in the
        monograph so a reviewer can grep the doc for a test name."""
        text = generate_monograph()
        for inv in REGISTRY.invariants:
            for test_id in inv.tests:
                assert test_id in text, (
                    f"test {test_id} bound to {inv.id} is not surfaced in the monograph"
                )

    def test_honest_naming_test_ids_appear_in_output(self) -> None:
        text = generate_monograph()
        for hn in REGISTRY.honest_naming:
            for test_id in hn.tests:
                assert test_id in text, (
                    f"test {test_id} bound to {hn.id} is not surfaced in the monograph"
                )


# ---------------------------------------------------------------------------
# 7. Round-trip via write_monograph.
# ---------------------------------------------------------------------------


class TestWriteRoundTrip:
    def test_write_monograph_to_tmp(self, tmp_path: Path) -> None:
        out = tmp_path / "monograph.md"
        result = write_monograph(out)
        assert result == out
        assert out.is_file()
        text = out.read_text(encoding="utf-8")
        assert text == generate_monograph()

    def test_write_creates_parent_dirs(self, tmp_path: Path) -> None:
        nested = tmp_path / "nested" / "dirs" / "monograph.md"
        write_monograph(nested)
        assert nested.is_file()


# ---------------------------------------------------------------------------
# 8. Output is non-trivial.
# ---------------------------------------------------------------------------


class TestNonTrivial:
    def test_output_has_section_headings(self) -> None:
        text = generate_monograph()
        for heading in (
            "## Table of contents",
            "## Gate state machine",
            "## Hard invariants",
            "## Honest-naming contracts",
        ):
            assert heading in text

    def test_output_ends_with_single_newline(self) -> None:
        text = generate_monograph()
        assert text.endswith("\n")
        assert not text.endswith("\n\n")
