"""M1 — system-invariant monograph generator.

This module emits a single canonical Markdown document — the
**System Invariants Monograph** — that walks the loaded
:class:`~neurophase.governance.invariants.InvariantRegistry` and
the :class:`~neurophase.governance.state_machine.StateMachineSpec`
and renders every load-bearing contract in one place. The output
is documentation in the strict sense of doctrine item *"a system
that cannot describe itself in one place is not yet a system."*

The generator is **deterministic**: the same registry + same
state machine produce byte-identical output across runs and
machines. The on-disk doc at
``docs/monograph/INVARIANTS_MONOGRAPH.md`` is committed alongside
the source, and a CI test asserts the live generator output
matches the committed doc — so any new HN added to
``INVARIANTS.yaml`` without a corresponding monograph regeneration
fails CI immediately.

Why this exists
---------------

Until M1, the load-bearing contracts of ``neurophase`` lived
across:

* ``INVARIANTS.yaml`` — machine-readable but not human-narrative.
* ``STATE_MACHINE.yaml`` — formal spec, dense.
* ``docs/EVOLUTION_BOARD.md`` — strategy + governance.
* ``docs/TASK_MAP.md`` — work plan.
* ``docs/theory/*.md`` — per-topic technical depth.

A reviewer who wanted to answer *"what does the system promise,
end to end?"* had to read all of those. The monograph collapses
that into one navigable surface.

What the monograph contains
---------------------------

1. **Header** — schema version, total invariant count, total
   honest-naming contract count, generation marker.
2. **Table of contents** — hyperlink anchors to every section.
3. **Gate state machine** — every state from ``STATE_MACHINE.yaml``
   with its transitions, rendered as a Markdown table.
4. **Hard invariants** — each ``Invariant`` with severity ``HARD``,
   in registry order.
5. **Advisory invariants** — each ``Invariant`` with severity
   ``ADVISORY``.
6. **Honest-naming contracts** — every ``HonestNamingContract``,
   sorted by id (HN1, HN2, …).
7. **Per-contract section** — one heading per contract carrying:
   the statement, the enforcement sites (path:symbol), the bound
   pytest node ids, and the documentation paths.

What the monograph does NOT contain
-----------------------------------

* No prose interpretation. The monograph reflects the registry
  verbatim — if you want narrative, the registry's ``statement``
  fields are the narrative. The generator does not paraphrase.
* No diagrams. Mermaid lives in ``docs/diagrams/``; the
  monograph cross-references those files but does not embed
  them. (Embedding would couple the generator to the diagram
  layout and break the byte-determinism guarantee.)
* No test results. A failing test does not change the monograph
  — the monograph documents what the contracts *are*, not
  whether they *passed* on the latest CI run.

Determinism contract (HN29)
---------------------------

* :func:`generate_monograph` is a pure function of its inputs.
  No clocks, no environment lookups, no random ordering. The
  output bytes for a fixed registry + state machine are stable
  across Python versions, OS, locale, and time of day.
* The committed ``docs/monograph/INVARIANTS_MONOGRAPH.md`` must
  equal the live generator output byte-for-byte. The HN29 test
  binds this as a CI guard.
* The generator MUST iterate the registry in file order
  (preserving the hand-maintained ordering of
  ``INVARIANTS.yaml``) and the honest-naming contracts in id
  order (HN1, HN2, …). Both are deterministic given the inputs.
"""

from __future__ import annotations

from pathlib import Path
from typing import Final

from neurophase.governance.invariants import (
    HonestNamingContract,
    Invariant,
    InvariantRegistry,
    InvariantSeverity,
    load_registry,
)
from neurophase.governance.state_machine import (
    StateMachineSpec,
    load_state_machine,
)

#: Canonical path of the committed monograph file relative to
#: the repository root.
MONOGRAPH_PATH: Final[Path] = (
    Path(__file__).resolve().parent.parent.parent / "docs" / "monograph" / "INVARIANTS_MONOGRAPH.md"
)

#: Stable header marker. The CI test grep-asserts this so a
#: hand-edited monograph cannot impersonate the generator.
GENERATED_HEADER_MARKER: Final[str] = (
    "<!-- GENERATED BY neurophase.governance.monograph — DO NOT EDIT BY HAND -->"
)

__all__ = [
    "GENERATED_HEADER_MARKER",
    "MONOGRAPH_PATH",
    "generate_monograph",
    "write_monograph",
]


def generate_monograph(
    *,
    registry: InvariantRegistry | None = None,
    state_machine: StateMachineSpec | None = None,
) -> str:
    """Render the canonical Markdown monograph.

    Parameters
    ----------
    registry
        Optional pre-loaded :class:`InvariantRegistry`. When
        ``None``, loads from the canonical
        ``INVARIANTS.yaml``.
    state_machine
        Optional pre-loaded :class:`StateMachineSpec`. When
        ``None``, loads from the canonical
        ``STATE_MACHINE.yaml``.

    Returns
    -------
    str
        The full Markdown text, ending with a single newline.
        Determinism guarantee: same inputs → byte-identical
        output.
    """
    reg = registry if registry is not None else load_registry()
    spec = state_machine if state_machine is not None else load_state_machine()

    parts: list[str] = []
    parts.append(GENERATED_HEADER_MARKER)
    parts.append("")
    parts.append("# neurophase — System Invariants Monograph")
    parts.append("")
    parts.append(_render_summary(reg, spec))
    parts.append("")
    parts.append("## Table of contents")
    parts.append("")
    parts.extend(_render_toc(reg, spec))
    parts.append("")

    # 1. Gate state machine.
    parts.append("## Gate state machine")
    parts.append("")
    parts.extend(_render_state_machine(spec))
    parts.append("")

    # 2. Hard invariants.
    parts.append("## Hard invariants")
    parts.append("")
    parts.append(
        "These contracts must hold at every tick. A violation in any "
        "hard invariant is a load-bearing safety failure and is bound "
        "to ≥ 1 pytest node id."
    )
    parts.append("")
    hard = [i for i in reg.invariants if i.severity is InvariantSeverity.HARD]
    for inv in hard:
        parts.extend(_render_invariant(inv))
        parts.append("")

    # 3. Advisory invariants.
    parts.append("## Advisory invariants")
    parts.append("")
    parts.append(
        "Advisory invariants route execution to a non-permissive but "
        "semantically distinct state (e.g. UNNECESSARY) rather than "
        "blocking outright."
    )
    parts.append("")
    advisory = [i for i in reg.invariants if i.severity is InvariantSeverity.ADVISORY]
    if advisory:
        for inv in advisory:
            parts.extend(_render_invariant(inv))
            parts.append("")
    else:
        parts.append("_(none currently registered)_")
        parts.append("")

    # 4. Honest-naming contracts.
    parts.append("## Honest-naming contracts")
    parts.append("")
    parts.append(
        "Non-permission contracts that constrain naming, behaviour, "
        "or documentation. Every contract is bound to ≥ 1 pytest "
        "node id and is enforced by CI."
    )
    parts.append("")
    # Sort by numeric id suffix for stable ordering across the
    # alphabetic-vs-numeric mix in INVARIANTS.yaml.
    sorted_hn = sorted(reg.honest_naming, key=_hn_sort_key)
    for hn in sorted_hn:
        parts.extend(_render_honest_naming(hn))
        parts.append("")

    parts.append("---")
    parts.append("")
    parts.append(
        "_This document is generated from ``INVARIANTS.yaml`` and "
        "``STATE_MACHINE.yaml`` by "
        "``neurophase.governance.monograph.generate_monograph()``. "
        "Do not edit by hand — regenerate with the M1 generator and "
        "commit the result._"
    )
    parts.append("")
    return "\n".join(parts)


def write_monograph(
    path: Path | str | None = None,
    *,
    registry: InvariantRegistry | None = None,
    state_machine: StateMachineSpec | None = None,
) -> Path:
    """Write the freshly generated monograph to disk.

    Returns the resolved path. The output is byte-identical
    across runs for the same registry + state machine.
    """
    out_path = Path(path) if path is not None else MONOGRAPH_PATH
    out_path.parent.mkdir(parents=True, exist_ok=True)
    text = generate_monograph(registry=registry, state_machine=state_machine)
    out_path.write_text(text, encoding="utf-8")
    return out_path


# ---------------------------------------------------------------------------
# Section renderers — pure functions over typed records.
# ---------------------------------------------------------------------------


def _render_summary(registry: InvariantRegistry, state_machine: StateMachineSpec) -> str:
    n_hard = sum(1 for i in registry.invariants if i.severity is InvariantSeverity.HARD)
    n_advisory = sum(1 for i in registry.invariants if i.severity is InvariantSeverity.ADVISORY)
    n_hn = len(registry.honest_naming)
    n_states = len(state_machine.states)
    n_transitions = len(state_machine.transitions)
    return (
        f"**Schema version:** {registry.version}  \n"
        f"**Hard invariants:** {n_hard}  \n"
        f"**Advisory invariants:** {n_advisory}  \n"
        f"**Honest-naming contracts:** {n_hn}  \n"
        f"**Gate states:** {n_states}  \n"
        f"**Gate transitions:** {n_transitions}"
    )


def _render_toc(registry: InvariantRegistry, state_machine: StateMachineSpec) -> list[str]:
    out: list[str] = []
    out.append("- [Gate state machine](#gate-state-machine)")
    out.append("- [Hard invariants](#hard-invariants)")
    for inv in registry.invariants:
        if inv.severity is InvariantSeverity.HARD:
            out.append(f"  - [{inv.id} — {inv.symbol}](#{_anchor(inv.id)})")
    out.append("- [Advisory invariants](#advisory-invariants)")
    for inv in registry.invariants:
        if inv.severity is InvariantSeverity.ADVISORY:
            out.append(f"  - [{inv.id} — {inv.symbol}](#{_anchor(inv.id)})")
    out.append("- [Honest-naming contracts](#honest-naming-contracts)")
    for hn in sorted(registry.honest_naming, key=_hn_sort_key):
        out.append(f"  - [{hn.id}](#{_anchor(hn.id)})")
    return out


def _render_state_machine(spec: StateMachineSpec) -> list[str]:
    out: list[str] = []
    out.append("### States")
    out.append("")
    out.append("| State | Semantic | Execution allowed |")
    out.append("|---|---|---|")
    for state in spec.states:
        flag = "✓" if state.execution_allowed else "✗"
        out.append(f"| `{state.name}` | {state.semantic} | {flag} |")
    out.append("")
    out.append("### Transitions (priority order)")
    out.append("")
    out.append("| Priority | From | Trigger | → To | Invariant |")
    out.append("|---|---|---|---|---|")
    sorted_transitions = sorted(spec.transitions, key=lambda t: t.priority)
    for t in sorted_transitions:
        invariant = t.invariant or "—"
        out.append(
            f"| {t.priority} | `{t.from_state}` | {t.trigger} | `{t.target}` | {invariant} |"
        )
    return out


def _render_invariant(inv: Invariant) -> list[str]:
    out: list[str] = []
    out.append(f"### {inv.id} — {inv.symbol}")
    out.append("")
    out.append(f"**Statement.** {inv.statement}")
    out.append("")
    out.append(f"**Severity.** `{inv.severity.value}`")
    out.append("")
    out.append(f"**Introduced in.** {inv.introduced_in}")
    out.append("")
    out.append("**Enforcement sites:**")
    out.append("")
    for site in inv.enforced_in:
        out.append(f"- `{site.path}::{site.symbol}`")
    out.append("")
    out.append(f"**Bound tests** ({len(inv.tests)}):")
    out.append("")
    for test in inv.tests:
        out.append(f"- `{test}`")
    out.append("")
    if inv.docs:
        out.append("**Documentation:**")
        out.append("")
        for doc in inv.docs:
            out.append(f"- `{doc}`")
    return out


def _render_honest_naming(hn: HonestNamingContract) -> list[str]:
    out: list[str] = []
    out.append(f"### {hn.id}")
    out.append("")
    out.append(f"**Statement.** {hn.statement}")
    out.append("")
    out.append("**Enforcement sites:**")
    out.append("")
    for site in hn.enforced_in:
        out.append(f"- `{site.path}::{site.symbol}`")
    out.append("")
    out.append(f"**Bound tests** ({len(hn.tests)}):")
    out.append("")
    for test in hn.tests:
        out.append(f"- `{test}`")
    out.append("")
    if hn.docs:
        out.append("**Documentation:**")
        out.append("")
        for doc in hn.docs:
            out.append(f"- `{doc}`")
    return out


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _anchor(label: str) -> str:
    """Convert an id like ``HN23`` to a Markdown anchor like ``hn23``.

    GitHub anchors lower-case and strip non-alphanumeric except
    hyphens. Our ids are simple enough that lowercasing is
    sufficient.
    """
    return label.lower().replace(" ", "-")


def _hn_sort_key(hn: HonestNamingContract) -> tuple[int, str]:
    """Sort honest-naming contracts by numeric suffix.

    ``HN1`` < ``HN2`` < ``HN10`` < ``HN22``. Falls back to
    string sort if the id has no integer suffix.
    """
    prefix = "HN"
    if hn.id.startswith(prefix):
        suffix = hn.id[len(prefix) :]
        try:
            return (int(suffix), hn.id)
        except ValueError:
            pass
    return (10**9, hn.id)
