"""Phase Locking Value — the falsification metric.

    PLV = |mean( exp(i · (φ_x(t) − φ_y(t))) )|,   PLV ∈ [0, 1]

    0 → no phase relationship (random phase difference)
    1 → perfect phase locking

The falsifiable predicate of the neurophase hypothesis:

    PLV(φ_neural, φ_market) > 0   on held-out intraday data.

Significance is assessed via a surrogate test over random cyclic shifts
of ``phi_y``, which preserves its autocorrelation structure while
destroying cross-signal phase locking.

INVARIANT I2: PLV must always be computed on held-out data.
              In-sample PLV is not reported.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import numpy.typing as npt

FloatArray = npt.NDArray[np.float64]


@dataclass(frozen=True)
class PLVResult:
    """Significance-tested PLV result.

    Attributes
    ----------
    plv : float
        Observed Phase Locking Value in [0, 1].
    p_value : float
        Proportion of surrogate PLVs greater or equal to the observed value.
    n_surrogates : int
        Number of surrogate samples used.
    significant : bool
        True when ``p_value < alpha``.
    alpha : float
        Significance level used.
    """

    plv: float
    p_value: float
    n_surrogates: int
    significant: bool
    alpha: float


def plv(phi_x: npt.ArrayLike, phi_y: npt.ArrayLike) -> float:
    """Compute the Phase Locking Value between two phase series.

    Parameters
    ----------
    phi_x, phi_y : array_like, shape (T,)
        Instantaneous phase series in radians.

    Returns
    -------
    float
        PLV in [0, 1].

    Raises
    ------
    ValueError
        If the two series have different lengths or are empty.
    """
    x = np.asarray(phi_x, dtype=np.float64)
    y = np.asarray(phi_y, dtype=np.float64)
    if x.shape != y.shape:
        raise ValueError(f"phi_x and phi_y must have the same shape, got {x.shape} vs {y.shape}")
    if x.size == 0:
        raise ValueError("phase series must be non-empty")
    return float(np.abs(np.mean(np.exp(1j * (x - y)))))


def plv_significance(
    phi_x: npt.ArrayLike,
    phi_y: npt.ArrayLike,
    n_surrogates: int = 1000,
    alpha: float = 0.05,
    seed: int = 42,
) -> PLVResult:
    """Assess statistical significance of PLV via a surrogate test.

    The null hypothesis is that ``phi_x`` and ``phi_y`` have no consistent
    phase relationship. Surrogates are generated by random cyclic shifts
    of ``phi_y``, which preserves its autocorrelation structure while
    destroying cross-signal phase locking.

    Parameters
    ----------
    phi_x, phi_y : array_like, shape (T,)
        Phase series computed on held-out data only.
    n_surrogates : int
        Number of surrogate samples.
    alpha : float
        Significance level in (0, 1).
    seed : int
        Seed for the PRNG driving the cyclic shifts.

    Returns
    -------
    PLVResult
    """
    if n_surrogates < 1:
        raise ValueError(f"n_surrogates must be >= 1, got {n_surrogates}")
    if not 0.0 < alpha < 1.0:
        raise ValueError(f"alpha must be in (0, 1), got {alpha}")
    x = np.asarray(phi_x, dtype=np.float64)
    y = np.asarray(phi_y, dtype=np.float64)
    observed = plv(x, y)
    rng = np.random.default_rng(seed)
    T = y.size
    surrogate = np.empty(n_surrogates, dtype=np.float64)
    for i in range(n_surrogates):
        shift = int(rng.integers(1, T))
        surrogate[i] = float(np.abs(np.mean(np.exp(1j * (x - np.roll(y, shift))))))
    p_value = float(np.mean(surrogate >= observed))
    return PLVResult(
        plv=observed,
        p_value=p_value,
        n_surrogates=n_surrogates,
        significant=p_value < alpha,
        alpha=alpha,
    )


def rolling_plv(
    phi_x: npt.ArrayLike,
    phi_y: npt.ArrayLike,
    window: int,
) -> FloatArray:
    """Compute PLV in a rolling window.

    Parameters
    ----------
    phi_x, phi_y : array_like, shape (T,)
    window : int
        Window length in samples. Must be positive and ≤ T.

    Returns
    -------
    FloatArray, shape (T − window + 1,)
    """
    if window <= 0:
        raise ValueError(f"window must be positive, got {window}")
    x = np.asarray(phi_x, dtype=np.float64)
    y = np.asarray(phi_y, dtype=np.float64)
    if x.shape != y.shape:
        raise ValueError(f"phi_x and phi_y must have the same shape, got {x.shape} vs {y.shape}")
    T = x.size
    if window > T:
        raise ValueError(f"window={window} larger than series length={T}")
    n_out = T - window + 1
    result = np.empty(n_out, dtype=np.float64)
    for i in range(n_out):
        result[i] = float(np.abs(np.mean(np.exp(1j * (x[i : i + window] - y[i : i + window])))))
    return result
